### ISSUE TITLE
[1.16.5] Worktable recipes invalid and don't exist

### ISSUE THREAD

**Issue by MundM2007** [InfernalCoding/EidolonDataRecipesComplete-Master#9]
When using This mod with Eidolon Rebrewed all worktable recipes will be removed. This happens on a profile with just the dependency mods. Inside of a bigger modpack I get the following error in the kubejs logs:
```
[21:35:28] [WARN ] Failed to parse recipe 'eidolon:unholy_effigy[eidolon:worktable]'! Falling back to vanilla: java.lang.IllegalStateException: Not a JSON Object: [" S ","TTT"," T "]
[21:35:28] [WARN ] Failed to parse recipe eidolon:unholy_effigy[eidolon:worktable]:
[21:35:28] [ERR  ] java.lang.IllegalStateException: Not a JSON Object: [" S ","TTT"," T "]
[21:35:28] [ERR  ] 	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
[21:35:28] [ERR  ] 	at elucent.eidolon.recipe.WorktableRecipeSerializer.read(WorktableRecipeSerializer.java:21)
[21:35:28] [ERR  ] 	at elucent.eidolon.recipe.WorktableRecipeSerializer.func_199425_a_(WorktableRecipeSerializer.java:18)
[21:35:28] [ERR  ] 	at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:141)
```

**Comment by MundM2007** [comment]
@InfernalCoding any ETA on when this will be fixed? This is for version 1.16.5

**Comment by InfernalCoding** [comment]
I've veered away from working on Eidolon for a while so I don't know yet.

**Comment by InfernalCoding** [comment]
I've veered away from working on Eidolon for a while so I don't know yet.

**Comment by MundM2007** [comment]
Okay, that's understandable. Only do it if you have the motivation and time
